# Project information
site_name: SubterraNova
site_url: 'wiebren.space/SubterraNova'
site_description: 'SubterraNova, a project of Wiebren-3.'
site_author: 'Wiebren-3'

# Copyright
copyright: Copyright &copy; 2023 - Wiebren-3

# Repository
repo_url: 'https://github.com/Wiebren-3/SubterraNova/'
repo_name: 'Wiebren-3/SubterraNova'

google_analytics: ['UA-167800475-3', 'wiebren.space/SubterraNova']

# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.webp
  custom_dir: docs/overrides
  language: nl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - toc.follow
    - content.action.edit
    - content.action.view
  extra:
    analytics:
      provider: google
      property: UA-167800475-3

plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Uitleg: uitleg.md
  - Bouwplan: bouwplan.md
    - Bouwtekeningen: bouwplan/bouwtekening.md
    - Bouwplan: bouwplan/index.md
  - 3D Model: 3doverview.md
